version: '3.8'

services:
  build-go:
    image:  golang:1.21-alpine
    volumes:
      - ./:/app
    working_dir: /app
    command: go build -o /app/dist/sanepar-falta-agua .
    network_mode: "host"